text_list = [{ //ind 0
        "consent_form_naturalistic": "DARTMOUTH COLLEGE<br>Naturalistic Cognition<br><br>RESEARCH PROJECT INFORMATION SHEET<br>This research project is being conducted by researchers from the Department of Psychological &amp; Brain Sciences at Dartmouth College, Hanover, NH, USA.&nbsp; This study aims to understand how individuals respond to movies and stories, and how their responses relate to aspects of their personality, cognitive abilities, and other traits.<br><br>Your participation is voluntary.&nbsp; Participation involves watching videos, reading or listening to stories, playing simple video games and other computerized tasks, answering questions about yourself, and similar activities You may choose to not answer any or all questions concerning personal or demographic information (age, gender, race, ethnicity, location, handedness etc.) as well as your opinions or feelings about the presented photos, audios, videos or any other survey material. However, you may be required to answer third-person questions relating to the task (e.g. 'Was there a social interaction in the presented video?').&nbsp;&nbsp; You must be 18 or older to participate. You may immediately end your participation if any aspect of the research procedure makes you too uncomfortable to continue. If you end your participation prematurely due to discomfort or technical difficulties, please contact the researcher to make sure you receive your payment. You may contact the researcher Emily Finn at emily.s.finn@dartmouth.edu.<br><br>The information collected will be anonymous and no identifying information will be stored with the data collected during the experiment. Identifying information will not be used in any presentation or paper written about this project and such presentations will represent the aggregation of data from groups of people.&nbsp;<br><br>Because your responses will not be individually identified, we will not be providing you with personal feedback or referrals based on any of your answers. We will not be monitoring your answers to any items, including questions about suicidality and self-harm, either in real time or after your participation is complete. If you are in crisis, and need immediate support or intervention, call, or go the website of the&nbsp;National Suicide Prevention Lifeline&nbsp;(1-800-273-8255).&nbsp;Trained crisis workers are available to talk 24 hours a day, 7 days a week.&nbsp;<br><br>For general information on mental health and to locate treatment services in your area, call the Substance Abuse and Mental Health Services Administration (SAMHSA) Treatment Referral Helpline at 1-800-662-HELP (4357). SAMHSA also has a&nbsp;Behavioral Health Treatment Locator&nbsp;on its website that can be searched by location.<br><br>Questions about this project may be directed to:&nbsp;<br>Emily Finn, Principal Investigator<br>HB 6207, Moore Hall, Hanover, NH 03755.<br>Email: emily.s.finn@dartmouth.edu&nbsp;"

    }, { // ind 1

        "devices_off_1": "<p>The survey has been optimized for Google Chrome and you may not be able to submit the survey with other browsers, so please switch to Chrome before you begin.</p>",
        "devices_off_2": "<style>p{text-align: left;}</style><p>You must pay full attention for the next 30 minutes, so please<br>  (1) mute all notifications and close open tabs,<br>(2) sit comfortably,<br>  (3) wear glasses or contact lenses if you use them, and <br>  (4) check that all mouse controls work. <br> <br> <strong>Instruction pages time out after some time, so please move through quickly where possible. </strong></p>"

    }, { //ind 2

        "instructions_txt_a": '<div><video style="border:5px solid black" id="anim_instr" loop width="600" autoplay><source src= "demo_animations/instrmim90.webm" type="video/webm"></video><strong><br>If you do not see the animation above, please exit now - you will not be able to submit the survey to Prolific without this.</strong><p>In this survey, you will watch several short animations (no audio) such as the one above. Each animation has two circles moving on the screen. In some of the animations, the motion can resemble a chase or pursuit-like behavior, and in others, the motion will seem more random.</p></div> ',

        "instructions_txt_b": '<p>Before proceeding, please zoom in/out your browser until the width of the video frame above approximately matches that of a credit card. Now please do not change this until the end of the survey.<br> There will be 84 animations in all, and you get short breaks to rest your eyes intermittently.<br>Unless you are at one of these breaks, do keep your eyes on the screen.</p><p><input type=checkbox id=instructions_checkbox required/> <strong> Understood. </strong> </p>'

    }, { //ind 3

        "instructions_q1": '<div style="width:600px;"><p><strong>After each animation, you get one question: <br> Did you see a social interaction, or were the circles moving randomly?<br>Indicate your choice on the continuous bar below.</strong><br/><br/> Where you place the marker on the bar indicates both (i) <i>what</i> you see and (ii) <i>how confident</i> you feel about this. Few examples below: <br><img src="expt_material/instructions/all.png" width="600"></p><p>Now try moving the cursor around on the bar.<br>Remember that you can use the <i>whole</i> bar.</p></div>',
    }

]